### ISSUE TITLE
Podman driver improvements (meta issue)

### ISSUE THREAD

**Issue by mikenomitch** [hashicorp/nomad-driver-podman#220]
This is a meta issue for a collection of work we intend to do over the Nomad 1.6 development cycle to improve the Podman Driver. This list is meant to give users visibility into what might be coming next, but is subject to change:

- [x] https://github.com/hashicorp/nomad-driver-podman/issues/160
- [x] https://github.com/hashicorp/nomad-driver-podman/issues/173
- [x] https://github.com/hashicorp/nomad-driver-podman/issues/36
- [ ] Upsert packs with podman variations
- [ ] https://github.com/hashicorp/nomad-driver-podman/issues/47
- [x] https://github.com/hashicorp/nomad-driver-podman/issues/50
- [x] https://github.com/hashicorp/nomad-driver-podman/pull/212

**Comment by jdoss** [comment]
@mikenomitch can https://github.com/hashicorp/nomad-driver-podman/issues/185 please get added to this list or tacked into the CSI topic? 😄

**Comment by mikenomitch** [comment]
Closing as done!
